# This workflow will build and upload WMCore core services to the production PYPY
# based on tag releases

on:
  push:
    tags:
      - '*'

jobs:
  build_and_publish_services:
    strategy:
      matrix:
        target: [wmagent, wmagent-devtools, wmcore, reqmon, reqmgr2, global-workqueue, acdcserver, reqmgr2ms]
    uses: ./.github/workflows/pypy_build_publish_template.yaml
    with:
      wmcore_component: ${{ matrix.target }}
    secrets:
      pypy_token: ${{ secrets.PYPY_PRODUCTION }}
